import type { MetadataRoute } from 'next';
import { SITE_URL } from '../lib/seo/site-config.ts';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: [
        '/',
        '/search',
        '/pricing',
        '/faq',
        '/responsible-outreach',
        '/privacy',
        '/terms',
        '/professors/',
        '/_next/static/',
        '/_next/image/',
        '/icon.svg',
      ],
      disallow: [
        '/admin',
        '/admin/',
        '/api/',
        '/dashboard',
        '/dashboard/',
        '/profile',
        '/profile/',
        '/campaigns',
        '/campaigns/',
        '/autopilot',
        '/autopilot/',
        '/tracker',
        '/tracker/',
        '/applications',
        '/applications/',
        '/inbox',
        '/inbox/',
        '/outreach',
        '/outreach/',
        '/onboarding',
        '/onboarding/',
        '/billing',
        '/billing/',
        '/checkout',
        '/checkout/',
        '/choose-plan',
        '/connectors',
        '/settings',
        '/settings/',
        '/login',
        '/signup',
        '/forgot-password',
      ],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
  };
}
